DROP DATABASE IF EXISTS TreeDB;
CREATE DATABASE TreeDB;

CREATE USER IF NOT EXISTS 'TreeDBAdmin'@'localhost' IDENTIFIED BY 'TreeDBPass';
GRANT INSERT, DELETE, SELECT ON TreeDB.* TO 'TreeDBAdmin'@'localhost';

USE TreeDB;

CREATE TABLE Users (
	UserID INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
	Username VARCHAR(64) UNIQUE NOT NULL,
	Salt BINARY(128) UNIQUE NOT NULL,
	HashedPass BINARY(255) NOT NULL,
	PRIMARY KEY (UserID)
);

CREATE TABLE AuthTokens (
	UserID INT UNSIGNED NOT NULL,
	AuthToken BINARY(64) UNIQUE NOT NULL DEFAULT(RANDOM_BYTES(64)),
	CreatedAt TIMESTAMP NOT NULL DEFAULT(CURRENT_TIMESTAMP),
	ExpiresAt TIMESTAMP NOT NULL DEFAULT(CURRENT_TIMESTAMP + INTERVAL '7' DAY),
	PRIMARY KEY (AuthToken),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Trees (
	UserID INT UNSIGNED NOT NULL,
	TreeID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	TreeName VARCHAR(64) NOT NULL,
	TreeDescription VARCHAR(1024) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL DEFAULT(CURRENT_TIMESTAMP),
	PRIMARY KEY (TreeID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Leaves (
	TreeID BIGINT UNSIGNED NOT NULL,
	LeafID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	LeafName VARCHAR(255) NOT NULL,
	LeafContent MEDIUMTEXT NOT NULL,
	PRIMARY KEY (LeafID),
	FOREIGN KEY (TreeID) REFERENCES Trees(TreeID)
);